name: recap
description: Recap - A Notification Reminder

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  image_picker: ^1.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^2.7.0
  path_provider: ^2.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700