name: recap
description: Recap - A Notification Remainder

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.4
  flutter_slidable: ^2.0.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  timezone: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FEFBFF"
  image: assets/icon.png
  color_dark: "#1B1B1F"
  image_dark: assets/icon.png

  android_12:
    color: "#FEFBFF"
    image: assets/icon.png
    color_dark: "#1B1B1F"
    image_dark: assets/icon.png