name: recap
description: Recap - A Notification Reminder

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+2
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^3.0.0
  image_picker: ^0.8.7+5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^2.3.2
  path_provider: ^2.0.15
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FEFBFF"
  image: assets/icon.png
  color_dark: "#1B1B1F"
  image_dark: assets/icon.png

  android_12:
    color: "#FEFBFF"
    image: assets/icon.png
    color_dark: "#1B1B1F"
    image_dark: assets/icon.png